apiVersion: ENC[AES256_GCM,data:q1g=,iv:ShqTEys/D0G/u0XSSjb8s/Cn073w5Nk9fjRNPYmWeQ0=,tag:abLnF5L0YNYKa8gQRfRoLw==,type:str]
kind: ENC[AES256_GCM,data:Z1VlkoFx,iv:4TSvodnB58JdssSVxv4tlp0MJNhTyjw2V0WxXYpxSYY=,tag:TMJyPmFv1G5aXu47pxU+3Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:F8nHdvJ+GTZ3Sb7XE6Q=,iv:WkkdokBSFEcOdYZL/Cb3qhveGBEljpKfVi65lFhL9Lc=,tag:EcLmns77ocFq7aKVDGGlRw==,type:str]
    namespace: ENC[AES256_GCM,data:66abRx7YC9G16tQ=,iv:VXWm6enswzaXKUD+xnZP2RwQG0SLkm6RcKjXvFareQs=,tag:rGlJ9OXY3lOARp95FZ+qGw==,type:str]
type: ENC[AES256_GCM,data:N1lpDA+eZ4l0TIzSVvPynpOg8eSJY830FPlcmDWJ,iv:CB16DMLCzznseLOSW+ib3rG+cdXYFwORPgHvtk2+oHQ=,tag:+FGgUuPcvU4/im+BuJAiAg==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:CUBHIkLJEO4uP7Nvswz2yzXM+G0suTfU44BOPNJhDXfN5B787Q6Q7oXtBvZfwKvcsl+5bG7OlbBVj0r9Z4fXANSW2VVEuuC8HvKw+xGQHRGR+ehyVC3qP1bNNmK9AKxqPmFTosF+PyO9pOpWMm9v648e2BCGOplYGTaIpl0Jf9YyDpERy0Gu17LSrkwVznqaXLzbDFkzY+/3usb8swrec+uEWsXtMOuQ6rMgC4G6YmLGxdxzFXjAQH44720T886K5JM6C08WMokedTzo,iv:46MvmQTb5KdgYkTKjFcofY5jDH2Rn4+zbwuuBwzUN5w=,tag:u/EZHcZpeiZyDJHciFe6VQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u74ps32m3mcvd6zjaw8w2p3wwfucz0r2rxrsxmq8ldlyv5lapgkqle505u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWnZkTCtpVGhJVHRtbk9O
            QjdrSXZoYmF6YUNnR3RaVk9wUS8zSytCNW1FCktENEtBTy9UTEt0NVFwMVkvWkVZ
            RThFcm9pd05jdGc0UVU2Z1VsRDVJalUKLS0tIE1PbEtFWTA4a2hIcStCWTljMHNP
            SG5ZdGtOYlN1NC85Z3g2VlBuY3JNcTgKssvM+8JuruyRhkU1GtkeVvRZZBmKIlMm
            3f7b2QoOx3sWpPpJJq+TAXAx56NgZh53GlbEWtMnccmDHL4m5AvcrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-15T11:27:07Z"
    mac: ENC[AES256_GCM,data:4TWmU/j/ICbSN8zG2k8MDtma7L+7uP2GwWZqzKjYJ/0G0hY8AcswVMaipmPvxaCC08voBuyhqjznyFRk1zRGO54ugXrIKqUb8PLSZkTXyi89S88YvJZ1g46pWhQ76H7dyR1sV5r8l/wnTNx1U3lXYbulUnHv/FL6cXE5HfZpye8=,iv:WyMpFVz1uZ/E41X1g/WYHYZNoYniu5/Bcz9hGjR/5zI=,tag:PSbh1Fg762h4o9vFWFhqxg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
